- hosts: lacework_servers
  become: yes
  tasks:
  - name: add apt signing key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 18E76630
      state: present
  - name: add lacework repository into source list
    apt_repository:
      repo: "deb [arch=amd64] https://packages.lacework.net/DEB/{{ ansible_distribution | lower  }}/{{ ansible_distribution_version }} {{ ansible_distribution_release }} main"
      filename: lacework
      state: present
  - name: install lacework datacollector
    apt:
      name: lacework
      state: latest
  - name: wait until /var/lib/lacework/config/ is created
    wait_for:
      path: /var/lib/lacework/config/
  - name: copy config.json
    copy:
      src: ./config.json
      dest: /var/lib/lacework/config/config.json
      owner: root
      group: root
      mode: 0644
